# Setup
title:               GIT BLOG
tagline:             'Choi yeon woo'
description:         'Hello! Here is blog of Choi yeon woo. Read my posts and give some comments for me!! I hope you enjoy my writings!!'
url:                 ''
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Choi yeon woo
  email:             christina1417@kookmin.ac.kr

# Gems
plugins:
  - jekyll-paginate
  

# Custom vars
version:             1.1.0
comments:
  provider: "disqus"
  disqus:
    shortname: "choiyeonwoo"
